"""
Section D - AI-Augmented Learning
STEP 1: BUILD WITH AI - Original code as generated by the AI tool.

PROMPT GIVEN TO THE AI TOOL:
"Write a Python program that generates a synthetic food delivery dataset with
at least 5 numeric columns and one categorical column (cuisine_type) using
NumPy, loaded into a Pandas DataFrame. Then produce a Seaborn pairplot of all
numeric columns, coloured by the categorical column, and save it as a PNG
file. Also compute the Pearson correlation matrix and display it as a Seaborn
heatmap with annotated cell values and a diverging colour palette, exported
as a separate PNG file at DPI 200 with a descriptive filename."
"""
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(5)
n = 150

# Generate a synthetic food delivery dataset
df = pd.DataFrame({
    'order_value': np.random.uniform(100, 800, n),
    'distance_km': np.random.uniform(1, 20, n),
    'delivery_time_mins': np.random.normal(30, 8, n),
    'rating': np.random.uniform(1, 5, n),
    'discount_pct': np.random.uniform(0, 30, n),
    # Simulate some missing/unknown cuisine entries in the real world
    'cuisine_type': np.random.choice(
        ['Fast Food', 'Indian', 'Chinese', None], n, p=[0.3, 0.3, 0.3, 0.1]
    ),
})

# Pairplot coloured by cuisine_type
pairplot = sns.pairplot(df, hue='cuisine_type')
pairplot.savefig('ai_pairplot_output.png')

# Correlation heatmap
numeric_df = df.select_dtypes(include='number')
corr = numeric_df.corr()

plt.figure(figsize=(7, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.savefig('ai_correlation_heatmap.png', dpi=200)

print("Done - pairplot and heatmap saved.")
